# Generated by Django 4.2.7 on 2023-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_category', models.CharField(max_length=120)),
                ('vehicle_sub_category', models.CharField(max_length=120)),
                ('old_plate_number', models.IntegerField(max_length=120)),
                ('vehicle_maker', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('fuel_type', models.CharField(max_length=120)),
                ('year_of_manufacturer', models.CharField(max_length=120)),
            ],
        ),
    ]
