# Generated by Django 4.2.7 on 2024-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_otherinfo_request_fancy_number_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherInfo',
        ),
        migrations.AddField(
            model_name='individual',
            name='middle_name',
            field=models.CharField(default=20, max_length=120),
            preserve_default=False,
        ),
    ]
