# Generated by Django 4.2.7 on 2024-01-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_otherinfo_individual_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('None', '-SELECT-'), ('Commercial', 'Commercial'), ('Government', 'Government'), ('Private', 'Private')], max_length=12),
        ),
    ]
