# Generated by Django 4.2.7 on 2024-01-20 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bio_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(help_text='yyyy/mm/dd'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='yyyy/mm/dd'),
        ),
    ]
