# Generated by Django 4.2.7 on 2024-01-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_bio_blood_group_alter_bio_class_of_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='passport',
        ),
        migrations.AddField(
            model_name='bio',
            name='profile',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
    ]
