# Generated by Django 4.2.7 on 2024-02-08 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_bio_class_of_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 8, 22, 28, 17, 23771), editable=False, help_text='yyyy/mm/dd'),
        ),
    ]
