# Generated by Django 4.2.7 on 2024-02-12 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_bio_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 12, 23, 41, 35, 211165), editable=False),
        ),
    ]
