# Generated by Django 4.2.7 on 2024-02-13 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_bio_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 13, 7, 16, 39, 71789), editable=False),
        ),
    ]
