# Generated by Django 4.2.7 on 2024-02-17 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_bio_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 17, 12, 49, 48, 580588), editable=False),
        ),
    ]
