# Generated by Django 4.2.7 on 2023-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profileimage_profile_profile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_profile'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
