# Generated by Django 4.2.7 on 2024-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_images_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('middlename', models.CharField(blank=True, max_length=120, null=True)),
                ('lastname', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=120)),
                ('local_government', models.CharField(max_length=120)),
                ('blood_group', models.CharField(max_length=120)),
                ('upload_driving_school_certificate', models.FileField(upload_to='driving_school_certificate/%y/%n/%d')),
                ('class_of_vehicle', models.CharField(max_length=120)),
                ('issue_date', models.CharField(max_length=120)),
                ('expiry_date', models.CharField(max_length=120)),
                ('passport', models.FileField(upload_to='passport/%y/%n/%d')),
            ],
        ),
    ]
