# Generated by Django 4.2.7 on 2024-01-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_bio_expiry_date_alter_bio_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='blood_group',
            field=models.CharField(choices=[(None, '---SELECT---'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bio',
            name='class_of_vehicle',
            field=models.CharField(choices=[(None, '---SELECT---'), ('Per', 'Personal'), ('offi', 'Official'), ('Trans', 'Transport')], max_length=120),
        ),
    ]
