# Generated by Django 4.2.7 on 2023-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_vehicle_old_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Disel', 'Disel'), ('Bio-Fuel', 'Bio-Fuel'), ('Others', 'Others')], max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Government', 'Government'), ('Private', 'Private')], max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacturer',
            field=models.IntegerField(max_length=120),
        ),
    ]
