# Generated by Django 4.2.7 on 2024-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_individual_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
