# Generated by Django 4.2.7 on 2024-02-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_vehicleinfo_user_vehicleinfo_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='vehicle',
        ),
    ]
