# Generated by Django 4.2.7 on 2024-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='old_plate_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_sub_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
