# Generated by Django 4.2.7 on 2024-01-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile'),
        ),
    ]
