# Generated by Django 4.2.7 on 2024-01-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_profile_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='profile',
            new_name='profiles',
        ),
    ]
