# Generated by Django 4.2.7 on 2024-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_profile_bio_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='upload_driving_school_certificate',
            field=models.FileField(upload_to='driving_school_certificate'),
        ),
    ]
