# Generated by Django 4.2.7 on 2024-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_bio_upload_driving_school_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='class_of_vehicle',
            field=models.CharField(choices=[(None, '---SELECT---'), ('Personal', 'Personal'), ('official', 'Official'), ('Transport', 'Transport')], max_length=120),
        ),
    ]
