# Generated by Django 4.2.7 on 2024-02-09 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_bio_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 10, 0, 39, 1, 982282), editable=False),
        ),
    ]
