# Generated by Django 4.2.7 on 2024-02-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_bio_firstname_remove_bio_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 10, 17, 29, 24, 681508), editable=False),
        ),
    ]
