# Generated by Django 4.2.7 on 2024-02-10 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_bio_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 10, 18, 42, 58, 356478), editable=False),
        ),
    ]
