# Generated by Django 4.2.7 on 2024-02-12 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_bio_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 12, 14, 33, 37, 624348), editable=False),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profiles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profiles'),
        ),
    ]
