# Generated by Django 4.2.7 on 2023-12-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_vehicle_year_of_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('engine_number', models.IntegerField()),
                ('policy_number', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('Bus', 'Bus'), ('Crane', 'Crane'), ('Motor cycle', 'Motor cycle'), ('Pick up', 'Pick up'), ('Salon', 'Salon'), ('SUV', 'SUV'), ('Tractor', 'Tractor'), ('Truck', 'Truck'), ('Van', 'Van'), ('Wagon', 'Wagon')], max_length=120)),
                ('chassis_no', models.IntegerField()),
                ('engine_capacity', models.CharField(choices=[('Above 3.0', 'Above 3.0'), ('Below 1.6', 'Below 1.6'), ('Between 1.6 and 2.0', 'Between 1.6 and 2.0'), ('Between 2.1 and 3.0', 'Between 2.1 and 3.0')], max_length=50)),
                ('tank_capacity', models.IntegerField()),
                ('odometer', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Disel', 'Disel'), ('Bio-Fuel', 'Bio-Fuel'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Government', 'Government'), ('Private', 'Private')], max_length=12),
        ),
    ]
