# Generated by Django 4.2.7 on 2023-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vehicleinfo_alter_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_license_number', models.IntegerField()),
                ('license_bearer_number', models.IntegerField()),
                ('state_of_plate_number_allocation', models.CharField(max_length=120)),
                ('request_fancy_number_plate', models.BooleanField()),
            ],
        ),
    ]
