# Generated by Django 4.2.7 on 2023-12-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_otherinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('identification_no', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('mobile_number', models.IntegerField()),
                ('state', models.CharField(max_length=120)),
                ('local_government', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('identification_no', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('mobile_number', models.IntegerField()),
                ('state', models.CharField(max_length=120)),
                ('local_government', models.CharField(max_length=120)),
            ],
        ),
    ]
