# Generated by Django 4.2.7 on 2024-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_vehicle_old_plate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_receipt_of_purchase', models.ImageField(upload_to='receipt of purchase')),
                ('Upload_proof_of_ownership', models.ImageField(upload_to='proof of ownership')),
                ('Upload_any_means_of_identification', models.ImageField(upload_to='nmeans of identification')),
                ('Upload_custom_paper', models.ImageField(upload_to='custom paper')),
                ('Upload_inurance_paper', models.ImageField(upload_to='insurance paper')),
                ('Upload_vehicle_image', models.ImageField(upload_to='vehicle image')),
                ('vehicle_identification_number', models.ImageField(upload_to='identification number')),
            ],
        ),
    ]
